JS - OOP part 2
stefangrgv/vcs-internship pull request #24
Opened 2022-06-24 12:13 UTC by stefangrgv

2022-06-27 05:37 UTC, vkolova requested changes
За първи опит е добре, но не ми харесва:
- Cмесването на логика за работа и ъпдейтване на UI; прочети за MVC pattern-a;
- Храна за размисъл -- как, подобрявайки архитектурата, можеш да спреш да ползваш толкова много глобални променливи за синхронизация? Условието на задачата е минимума, който трябва да се покрие, винаги можеш да добавиш още неща;
- UI-а е малко неясен. Похвално, че си тръгнал да имплементираш такъв, очаквах логване в конзолата, но по-информативно би било да се показва:
     - първо опашката, с малко по-добре форматирана информацията за поръчките
     - върху какво се работи в момента
     - приготвените пици и total-а на цените им.
- Имаш момент, където не се синхронизират нещата правилно и вместо да "готвиш", задържаш опашката и се трупат пици:
![Screenshot from 2022-06-27 08-33-32](https://user-images.githubusercontent.com/5569382/175867164-2c93cb4f-b759-4391-898a-03941b18037b.png)

2022-06-27 05:37 UTC, vkolova commented on 04_getting_started_js/pizzeria.js
> +        this._id = ordersMade;
Нямаш гаранция за уникалност на ID-тата. Помисли как можеш по-надеждно да генерираш уникални идентификатори (timestamp на създаване, някакъв друг начин с hash функция, и др.)

2022-06-27 05:37 UTC, vkolova commented on 04_getting_started_js/pizzeria.html
> +            width:33%;
Старай се да форматираш правилно CSS-а. Можеш да си сложиш `stylelint` за помощ :)

2022-06-27 05:37 UTC, vkolova commented on 04_getting_started_js/pizzeria.js
> +    ready ( callback ) {
Така като гледам, имплементацията на ready и start се различава малко от условието.

По условие:
```js
var pizza = new Pizza("Peperoni", 100 /*cost*/, 2000 /*timeToMake in ms = 2 seconds */);

var order = new PizzaOrder(pizza);
order.ready(function(p, o) {
  // the pizza is ready now
  o.getId(); // should return the unique id
});

order.start();
```
Което означава, че order предварително трябва да знае какво да изпълни преди да си извикал  `.start()`;

2022-06-27 05:37 UTC, vkolova commented on 04_getting_started_js/pizzeria.js
> +var quattroStagioni = new Pizza('Quattro Stagioni', 120, 2000);
Нещо много бързо ми се готвят тези пици, за да отговаря зададеното им време на това, което виждам...

Също така, по време на тестването ми се случи да има голяма опашка, но все пакнищо да не се приготвя.

2022-06-27 05:37 UTC, vkolova commented on 04_getting_started_js/point_sky.js
> +class Point {
Тази задача защо е тук?

2022-06-27 05:37 UTC, vkolova commented on 04_getting_started_js/robot.js
> +class Point {
И това защо е в този PR?

2022-06-27 05:37 UTC, vkolova commented on 04_getting_started_js/pizzeria.js
> +var ordersMade = 0;
`var` вече е доста излязло от мода :) Нека се придържаме към `let` и `const` от тук нататък?

2022-06-27 05:37 UTC, vkolova commented on 04_getting_started_js/pizzeria.js
> +var kitchenBusy = false;
Не ми харесва, че работиш с толкова много глобални променливи, особено, когато има как да го избегнеш.

Особено лоша практика е и да променяш стойността на въпросните променливи от вътрешни методи на класове.

2022-06-27 12:10 UTC, stefangrgv commented on 04_getting_started_js/pizzeria.js
> +    ready ( callback ) {
Не разбирам какво имаш предвид тук

2022-06-27 13:09 UTC, vkolova commented on 04_getting_started_js/pizzeria.js
> +    ready ( callback ) {
.ready() трябва предварително да запази callback-а, .start() след това да го изпълни.

2022-06-27 13:18 UTC, vkolova requested changes
Усложняваш си живота.
- Нямаш нужда от set и get методи.
- С тези статуси на пиците направи положението по-зле.
- **_Помисли по какъв начин да имаш по-добър контрол над целия workflow_** преди да започнеш да пишеш. Ако искаш, предложи идеи, ще обсъдим плюсове и минуси и дали са подходящи преди да започнеш да имплементираш.

2022-06-27 13:18 UTC, vkolova commented on 04_getting_started_js/styles.css
> +  font-size: 28;
Каква мерна единица?

2022-06-27 13:18 UTC, vkolova commented on 04_getting_started_js/pizzeria.js
> +        uiSetOrderPreparing(this.getPizza(), this);
Продължаваш да обвързваш UI и бизнес логика.

2022-06-27 13:18 UTC, vkolova commented on 04_getting_started_js/pizzeria.js
> +        this._id = Date.now() - startTime;
Защо? Не е ли достатъчно `Date.now()`?

2022-06-27 13:18 UTC, vkolova commented on 04_getting_started_js/pizzeria.js
> +const tickTime = 500; // ms
Нека спазваме правилото "Изнасяме в променлива, само ако иначе ще се повторим"

2022-06-28 11:51 UTC, vkolova commented on 04_getting_started_js/pizzeria2.js
> +        this.pendingOrders.push(new PizzaOrder(this.pizzas[randomInt(this.pizzas.length - 1)]));
const pizza = new Pizza(...)
pizza.ready(..)
this.pendingOrders.push(pizza)

2022-06-28 12:06 UTC, merged