Linklists with django
stefangrgv/vcs-internship pull request #35
Opened 2022-07-25 11:34 UTC by stefangrgv

2022-08-05 12:11 UTC, vkolova requested changes
- UI-за може да се подобри малко, поне да казва само по 1 път кой е логнат и да дава възможност за logout:

![Screenshot from 2022-08-05 14-26-47](https://user-images.githubusercontent.com/5569382/183068115-9a87cf93-e174-49cd-b1c6-6d9f8352e9bd.png)

- Опитах да създам списък с няколко линка вътре и влезе в някакъв безкраен цикъл, с пращане на заявки...

![Screenshot from 2022-08-05 14-28-30](https://user-images.githubusercontent.com/5569382/183068546-8df15af2-48b6-461f-abc6-b3272ea5bb45.png)

- Защо да не мога да създавам празни списъци?
- Не използвай `alert`, адски досадни са... handle-вай в UI-a грешките...


_**Като цяло не можах да тествам много от функционалността, защото не мога да създам списък....**_


Ето малко React how-to благинки :) [react-bits](https://github.com/vasanthk/react-bits)

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/apiRequests.js
> +  alert()
Този `alert`..
![image](https://user-images.githubusercontent.com/5569382/183073141-c7b56cf7-49f0-4475-8de0-a7651e1af352.png)

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/apiRequests.js
> +    body: JSON.stringify({
Мммм изобщо не ми харесва това изпращане на данни... Или намери начин да пращаш директно обект, или използвай axios.

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/apiRequests.js
> +  fetch('http://localhost:8000/api/createuser/', {
Утре ако се смени url-a на сървъра какво правим?

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/apiRequests.js
> +      window.location.href = '/login/';
Не разрешавам редиректване с window.location. Имаш react router, ползвай го, това му е идеята -- да се занимава с контрол над историята и локацията...

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/apiRequests.js
> +    alert(error);
:)

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/apiRequests.js
> +        window.location.href = '/myprofile/'
Същото като горе.

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/index.js
> +          <Route path=':id' element = {<LinkList mode = 'view' />} />
Ммм не е хубаво точно така да имаш само `:id`, сложи някакъв префикс, `list` или подобно. На останалите route-ове за списъци същото.

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/style.css
> +  -webkit-margin-end: 10px;
Защо добавяш `-webkit`, това плъгините на webpack трябва да го добавят сами?

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/style.css
> +  -webkit-margin-end: 10px;
А, разбрах -- този файл е резултат от процеснатия `style.scss`. Погрижи се само сорса да се записва и събмитва, тези .css файлове не трябва да ги има.

2022-08-05 12:11 UTC, vkolova commented on 06_django/frontend/src/withRouter.js
> +const withRouter = WrappedComponent => props => {
Ползваш ли го изобщо този компонент? Ако имаш нужда от него, правиш нещо грешно.

2022-08-05 12:11 UTC, vkolova commented on 06_django/linkbundle/api/permissions.py
> +                or (str(obj.owner) == str(request.user))):
Защо сравняваш потребители като стрингове? Би трябвало да работи с инстанции?

2022-08-05 12:17 UTC, stefangrgv commented on 06_django/frontend/src/withRouter.js
> +const withRouter = WrappedComponent => props => {
Ползвам го, за да взема id-то на списъка от адреса след domain name-a. Не открих друг начин да го направя, освен с ванила метода window.location.pathname, но съм сигурен че не трябва него да ползвам.

2022-08-05 12:19 UTC, vkolova commented on 06_django/frontend/src/withRouter.js
> +const withRouter = WrappedComponent => props => {
Трябва да ползваш useMatch > https://reactrouter.com/docs/en/v6/hooks/use-match

2022-08-15 07:01 UTC, stefangrgv commented on 06_django/frontend/src/withRouter.js
> +const withRouter = WrappedComponent => props => {
Но useMatch e hook и работи само за react function components, а ти ми беше казала за ползвам class components

2022-08-18 06:18 UTC, vkolova requested changes
Не знам какво точно се е променило, но проекта вече не може да се подкара на Node.js 14 изобщо, т.е. не мога да го тествам на моята машина.

Има много неща по кода и форматирането, които трябва да се изчистят. Някак си проекта стана няколко пъти по-зле, спрямо предната версия, която гледах.

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/CreateUser.js
> +    return ((passwordOne === passwordTwo &&
Помисли как да изчистиш малко кода тук, може и по-кратко и по-красиво да се напише.

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/CreateUser.js
> +  let userInfo = isUsernameOk() ? <></>
Ужасно форматиране!

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/CreateUser.js
> +    {userInfo}
Прието е информация за валидирането да се показва непосредствено под нещото, което се валидира. Т.е. `userInfo` под username полето, `emailInfo` под мейл полето и т.н.

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/Header.js
> +      {context.user.username === null ? 'navbar-guest' : 'navbar'}>
Това защо е толкова шано разделено на 2 реда?

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/LinkList.js
> +  React,
Импортите!

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/LinkList.js
> +          if (linkDbEntry === undefined) {
Тази проверка... 😕🤔

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/LinkList.js
> +  async function fetchList () {
`async/await`? 😕🤔

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/LinkList.js
> +      let newLinks = links.map((link) => {
Const!

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/LinkList.js
> +    let parsedURL = input.replace('www.', '');
JS има вграден клас за работа с URL-и, използвай го

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/LinkList.js
> +        l['thumbnail'] = formatURLInput(link['thumbnail']);
Защо има спейсове преди `'thumbnail'`

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/LinkList.js
> +    Trims the title of the links to ensure it fits the
Същото можеш да го постигнеш с CSS? И даже ще е по-добре, защото няма да си ограничен откъм бройка символи.

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/LinkList.js
> +        context.setModalBody('Success!');
Нещо не ми харесват тези модали, които контролираш от контекст....

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/LinkList.js
> +export default LinkList;
Тук се случват много лоши неща.
Самият факт, че файла ти е над 500 реда трябва да те подсеща, че не са наред нещата.

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/UserPanel.js
> +                        async () => {
НЕ!

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/UserPanel.js
> +                      () => context.showQuestionModal(
В никакъв случай не трябва да подаваш директно така arrow фунцкции на event handler-и! На всеки re-render на този списък, ще се създават нови инстанции на тези функциии! Пък ти даже и вътре още функции създаваш...

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/UserPanel.js
> +        () => navigate('/list/new/')
Плача с тези `onClick={() => ...}`

2022-08-18 06:18 UTC, vkolova commented on 06_django/frontend/src/apiRequests.js
> +    `${serverAddress}/api/lists/${id}/`, {
Не може ли да зададеш serverAddress като base url на axios?

2022-08-24 09:15 UTC, vkolova requested changes
Доста по-добре, но моля те, оправи форматирането.

2022-08-24 09:15 UTC, vkolova commented on 06_django/frontend/src/ChangePassword.js
> +    if (oldPassword === '') context.showMessageModal('Old password is required!');
Моля те не изпускай {} при if/else оператори. Става нечетимо.

2022-08-24 09:15 UTC, vkolova commented on 06_django/frontend/src/CreateUser.js
> +        if (typeof(errorContents.username) !== 'undefined') {
Не изплзвай undefined, за да проверяваш дали нещо го има или не. `!!` ще ти даде булев резултат.

2022-08-24 09:15 UTC, vkolova commented on 06_django/frontend/src/CreateUser.js
> +      {!isEmailOk() ? <div className='error-message'>Please enter a valid email.</div> : <></>}
Правиш много дълги редове, кода става нечетим. А що се отнася до тернарния оператор, предполага се ето така да го форматираш:
```javascript
{
    !isEmailOk()
        ? <div className='error-message'>Please enter a valid email.</div>
        : <></>
}
```

Понеже в случая нищо не връщаш и това е вариант:
```javascript
{
    !isEmailOk() && <div className='error-message'>Please enter a valid email.</div>
}
```

2022-08-24 09:15 UTC, vkolova commented on 06_django/frontend/src/LinkList/ListPanels/ContentsPanel.js
> +      context.showQuestionModal('Are you sure you want to delete this link?', 'Yes', deleteLink, 'No', clearDeleteId);
Отново, много дълги редове. Можеш да го разделиш на няколко, ето така
```javascript
someMethod(
   arg1,
   arg2,
   arg3,
   ...
)
```

2022-08-24 09:15 UTC, vkolova commented on 06_django/frontend/src/LinkList/ListPanels/ContentsPanel.js
> +    if (editId !== null) {
Не прави сравнения с null...

2022-08-24 09:15 UTC, vkolova commented on 06_django/frontend/src/LinkList/ListPanels/ContentsPanel.js
> +        {link.isMinimized ? <></> :
Лошо форматиране из този файл.

2022-08-24 09:15 UTC, vkolova commented on 06_django/frontend/src/LinkList/ListPanels/SaveDeletePanel.js
> +      } else if (response.response.status === 403) {
Изкарай `response.response.status` в променлива.

2022-08-24 11:11 UTC, vkolova commented on 06_django/frontend/src/LinkList/ListPanels/ContentsPanel.js
> +    newLinks[event.currentTarget.id].isMinimized =
Не дели присвояване на 2 реда, освен ако резултата не се калкулира от `? :`

2022-08-24 11:11 UTC, vkolova commented on 06_django/frontend/src/LinkList/ListPanels/SaveDeletePanel.js
> +      props.mode === 'new'
Слей редове 23 и 24

2022-08-24 11:11 UTC, vkolova commented on 06_django/frontend/src/LinkList/ListPanels/TitlePanel.js
> +        {props.owner === context.user.username ? (
? трябва да е в началото на нов ред.

2022-08-24 11:17 UTC, vkolova approved these changes

2022-08-24 11:18 UTC, merged